name: Build WebUI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          repository: Bread-Ch4n/FRM-s-WebUI-Source
      - uses: Bread-Ch4n/FRM-s-WebUI-Source/.github/workflows/build.yml@main
